### ISSUE TITLE
why there has no org.ciasaboark.tacere.billing.KeySet

### ISSUE THREAD

**Issue by leizhiyuan** [ciasaboark/Tacere#43]
I forked this project. It's very excellent, but why I can't find `KeySet` class which is imported by  `BugReportActivity`.

**Comment by ciasaboark** [comment]
`KeySet` contains private keys used during the in-app billing process, and thus won't be committed to the repository.  In order to compile the project, you will need to create the file in your fork and supply the following:
```java
public static final String GOOGLE_LICENSE_KEY = "your google key here"
public static final String SKU_UPGRADE_PRO = "sku for in pro version in-app purchase"
public static final String GITHUB_OAUTH = "your generated github oauth key"
```

If you don't plan on publishing the fork, then you can supply dummy keys.  If you want to remove any usage of `KeySet` then you will need to modify `LicenseCheckWrapper` and remove `BugReportActivity` and `ProUpgradeActivity`

**Comment by leizhiyuan** [comment]
Thank you.
